### ISSUE TITLE
Error handling not propagated

### ISSUE THREAD

**Issue by choco** [merged-js/solid-apollo#10]
I noticed that errors produced by the GraphQL call are not propagated correctly.

The main issues seems to be that in the subscription for the observables created through Apollo client, errors are thrown instead of the calling the `reject` method of the outer promise. The fix is to just use `reject` instead of throw when defining the subscription methods.

For example here https://github.com/merged-js/solid-apollo/blob/7188b8a504bd8b95cdf810c90b66bda6092ec992/src/createQuery.ts#L45-L51
it should be:
```ts
 error: error => { 
   reject(error) 
 }, 
 next: ({ data, error }) => { 
   if (error) { 
     reject(error)
   } 
```

**Comment by Torsten85** [comment]
Thanks for your input. I could reproduce this error and it should now be fixed in version `1.7.1`
