### ISSUE TITLE
Adding your library to apollo docs community integrations?

### ISSUE THREAD

**Issue by jpvajda** [merged-js/solid-apollo#11]
Hello! 

I'm the Staff Product Manager for Apollo Client 👋 

I'm really excited you created this library for Apollo + Solid.js. I'm really liking the approach Solid.js is taking and curious if it will gain popularity. Would you be interested in adding your library to our Community Integration section on our web client's main docs page:

https://www.apollographql.com/docs/react/

We accept PRs to our documentation site. 😄  

`docs file`https://github.com/apollographql/apollo-client/edit/main/docs/source/index.mdx

As a caveat: If you do add it, it may drive a lot of interest to your project, so if you feel it's not in a stable release state, adding it may not be something you are interested in at the moment, so just let us know! 

Thanks for the consideration!

**Comment by jpvajda** [comment]
@Torsten85 👋 I was just following up on this question. Just let me know what you think! I'd love to let users of Apollo Client know about this repository.

**Comment by Torsten85** [comment]
Hi @jpvajda and sorry for the late reply.

I would love to see this library added to the community integrations! Of course I cannot guaranteed that this is 100% stable (as I do this in my spare time) but I'm using it for quite a while now and didn't encountered any issues.

**Comment by jpvajda** [comment]
@Torsten85 I've added a reference to your library, feel free to close this issue now. Thanks again!

**Comment by Torsten85** [comment]
Thanks!
